# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d4ab4633442aabc9c587e41609e3b5908ba071b9ee2437201a62eb68ceb2d95924c8578da0b54fecf41ef5d0ad0b4d44b3f609300f01c984d029b83db3e46eb

test:
  secret_key_base: 0be457ee8661531e8c212460631bd227d355ab575ec3ee7ae71fd79fd57de7a22bca03c102cc2a033fce847e678f99e8376635131b04139dca23793dc0844a46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
